# Generated by Django 5.1.15 on 2026-04-17 21:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_id', models.CharField(max_length=100)),
                ('target_type', models.CharField(choices=[('person', 'Person'), ('place', 'Place')], max_length=10)),
                ('decision', models.CharField(choices=[('like', 'Like'), ('pass', 'Pass')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='users.user')),
            ],
            options={
                'verbose_name': 'Swipe',
                'verbose_name_plural': 'Swipes',
                'ordering': ['-created_at'],
            },
        ),
    ]
